### ISSUE TITLE
Cheatsheet for Vue does not show

### ISSUE THREAD

**Issue by NicoWeio** [rstacruz/cheatsheets#1049]
For some reason, https://devhints.io/vue won't show any content in various browsers.
Yet it does send over the cheatsheet content, as can be observed using curl.
This has already been reported in #783.

**Comment by G710** [comment]
Same for the [pacman](https://devhints.io/pacman) cheatsheet. You can inspect the content but everything is invisible.

It seems like the ```style.css``` is not found.

**Comment by G710** [comment]
Thank you for quickly fixing this. The issue can be closed :+1:
