### ISSUE TITLE
GraphQL is in wrong category

### ISSUE THREAD

**Issue by phakiller** [rstacruz/cheatsheets#1123]
Now, GraphQL is in `Database` category, but it is not related with any kind of Database.
As we can se in this [link](https://graphql.org), GraphQL is a Query Language for APIs, in fact is an especification.

I sugest to create a new category `GraphQL`, because we have most related projects for it.

**Comment by ojkelly** [comment]
I want to second this, GraphQL is not a `Database`.

Looking at the current list of categories, I'd suggest a new one called `API`.

**Comment by rstacruz** [comment]
:rofl: good catch! I'll bundle it with some others under API.
