### ISSUE TITLE
Cheatsheet request: kotlin

### ISSUE THREAD

**Issue by vladimir-petric** [rstacruz/cheatsheets#133]

**Comment by AdamMc331** [comment]
Hey @vladimir-petric Great idea! I've submit a PR, let me know what you think: https://github.com/rstacruz/cheatsheets/pull/724

**Comment by AdamMc331** [comment]
Also, any chance we can close this as a duplicate of https://github.com/rstacruz/cheatsheets/issues/94?

**Comment by chadwithuhc** [comment]
Closing in favor of #94
