### ISSUE TITLE
React cheatsheet

### ISSUE THREAD

**Issue by adamvaul** [rstacruz/cheatsheets#15]
You should add a tag at the end under the map that shows how you need to bind a reference to this if you want to refer to a function on the containing class.  Based off this page:
https://facebook.github.io/react/tips/communicate-between-components.html

**Comment by rstacruz** [comment]
Hmmm

**Comment by rstacruz** [comment]
https://github.com/rstacruz/cheatsheets/blob/gh-pages/react.md#lists here you mean?
