### ISSUE TITLE
Cheatsheet request: http status code

### ISSUE THREAD

**Issue by ablil** [rstacruz/cheatsheets#1654]
It would be amazing to add a cheatsheet of most used **http status code** and their meaning, categorized like the following:

* **1xx** informational response – the request was received, continuing process
* **2xx** successful – the request was successfully received, understood, and accepted
* **3xx** redirection – further action needs to be taken in order to complete the request
* **4xx** client error – the request contains bad syntax or cannot be fulfilled
* **5xx** server error – the server failed to fulfil an apparently valid request

**Comment by rstacruz** [comment]
You might like https://devhints.io/http-status :)
