### ISSUE TITLE
move-line-down/up keybindings include ctrl

### ISSUE THREAD

**Issue by drbergman** [rstacruz/cheatsheets#1703]
At least as of 1.58.0, it seems that the default keybindings for move-line-down/up include ctrl so they are ctrl-cmd-down and ctrl-cmd-up. They are listed on the cheatsheet without ctrl.

**Comment by rstacruz** [comment]
I have a feeling you're talking about the Atom cheatsheet.. I believe that should sorted out now :) Let me know if not!
