### ISSUE TITLE
Cheatsheet request: Latex

### ISSUE THREAD

**Issue by JordanDworaczyk** [rstacruz/cheatsheets#1715]
I noticed that there is not a cheat sheet for Latex (although I may be wrong). Assuming there is not perhaps we could add it to the list of possible cheat sheets to work on. Anyone else interested in a Latex cheat sheet?

**Comment by lukasMega** [comment]
duplicate of https://github.com/rstacruz/cheatsheets/issues/1691

**Comment by JordanDworaczyk** [comment]
Yes, this is a duplicate. I'll close this issue. Thanks!
