### ISSUE TITLE
Example issue - Desctructuring > Default values

### ISSUE THREAD

**Issue by scheinercc** [rstacruz/cheatsheets#173]
https://github.com/rstacruz/cheatsheets/blob/master/es6.md

`// math === 22, sci === 23, arts === 50`

=>

`// math === 22, sci === 33, arts === 50`

(sci === 33) ?

**Comment by lnfnunes** [comment]
![image](https://user-images.githubusercontent.com/2450417/43109199-ebde068c-8ebb-11e8-80c7-3c1460a05d88.png)

The example is correct, looks like it's already been fixed!
@rstacruz maybe this should be closed!

**Comment by scheinercc** [comment]
@lnfnunes thanks! I checked it as well & closing the ticket.
