### ISSUE TITLE
Cheatsheet request: CSS Grid

### ISSUE THREAD

**Issue by vinyll** [rstacruz/cheatsheets#175]
Such as [Grid cheatsheet from Malven](http://grid.malven.co/) though it misses a few Grid features (such as `area`)

**Comment by ruphaafd** [comment]
You can play with CSS grid in these following two resources as well:
[https://alialaa.github.io/css-grid-cheat-sheet/](https://alialaa.github.io/css-grid-cheat-sheet/)
[http://cssgridgarden.com/](http://cssgridgarden.com/)

**Comment by chadwithuhc** [comment]
CSS Grid is now available! https://devhints.io/css-grid

If you see anything you think needs changes or additions, please submit a PR.
