### ISSUE TITLE
Cheatsheet request: kubectl

### ISSUE THREAD

**Issue by psyll0n** [rstacruz/cheatsheets#2128]
Perhaps, a `kubectl` cheatsheet would be useful to many people.

**Comment by TzolkinB** [comment]
Duplicates: https://github.com/rstacruz/cheatsheets/issues/2128, https://github.com/rstacruz/cheatsheets/issues/1855, https://github.com/rstacruz/cheatsheets/issues/1805, https://github.com/rstacruz/cheatsheets/issues/1480, https://github.com/rstacruz/cheatsheets/issues/993, https://github.com/rstacruz/cheatsheets/issues/324

PR: https://github.com/rstacruz/cheatsheets/pull/2108
