### ISSUE TITLE
Cheatsheet request: PHP for Wordpress

### ISSUE THREAD

**Issue by kwaniie** [rstacruz/cheatsheets#280]
Hi Rico! I am currently designing a web application and I found your DevHints website today and your css/flexbox cheat sheets are really helpful for me! I was searching to see if you had one for PHP or PHP for Wordpress but they didn't come up so I clicked on the button to send the suggestion and request for one!

**Comment by pkvillanueva** [comment]
I don't think he has any PHP framework or CMS on his list.

**Comment by chadwithuhc** [comment]
Closing this in favor of original #226 

There is also a PHP sheet in the works
