### ISSUE TITLE
Broken links on index page

### ISSUE THREAD

**Issue by imcmahon** [rstacruz/cheatsheets#30]
Just a note that all the links on the cheatsheet homepage are broken, they're missing the /cheatsheets/ in the path. e.g.

http://ricostacruz.com/ansible-examples.html

Should be:

http://ricostacruz.com/cheatsheets/ansible-examples.html

Awesome set of cheatsheets though!

**Comment by rstacruz** [comment]
oh shame, layout is broken too

**Comment by rstacruz** [comment]
fixed!
