### ISSUE TITLE
Bug: Favicon Missing

### ISSUE THREAD

**Issue by qoomon** [rstacruz/cheatsheets#321]
Favicon is missing for https://devhints.io/

https://devhints.io/assets/favicon.png -> 404

**Comment by d0vi** [comment]
Can we make this happen?

**Comment by GeorgeWL** [comment]
why is this still even an issue after all this time?

**Comment by GitHub-Mike** [comment]
You can simply put a file "favicon.png" in the directory {root}/assets. See {root}/_includes/meta.html line 3. What is the problem here?

**Comment by qoomon** [comment]
I've created a PR #1023
