### ISSUE TITLE
Minor errors in bash cheatsheet

### ISSUE THREAD

**Issue by loxaxs** [rstacruz/cheatsheets#332]
At the end of the section (`Parameter expansions > Basics`)(https://github.com/rstacruz/cheatsheets/blob/master/bash.md#basics), there is the following codeblock:

    SRC="/path/to/foo.cpp"
    BASE=${STR##*/}   #=> "foo.cpp" (basepath)
    DIR=${SRC%$BASE}  #=> "/path/to" (dirpath)

It contains two errors:
Line 2: `STR` should be replaced by `SRC`
Line 3: `"/path/to"` should be replaced by `"/path/to/"`, or the trimming modifier should be changed from `$BASE` to `/$BASE`.

**Comment by chadwithuhc** [comment]
These have been fixed with a PR, thanks!
