### ISSUE TITLE
Brew cask in brew cheatsheet

### ISSUE THREAD

**Issue by sbuckleybonanno** [rstacruz/cheatsheets#35]
The "Updating caskroom" code on the hombrew.md uses the code "brew upgrade brew-cask" which is no longer how to upgrade cask. In fact, "brew upgrade" seems to update cask automatically now, so "brew upgrade brew-cask" is unnecessary.

**Comment by rstacruz** [comment]
Thanks! I'll remove all the cask stuff completely, they're not very important
