### ISSUE TITLE
How can we use it for our own cheatsheet management?

### ISSUE THREAD

**Issue by collegeimprovements** [rstacruz/cheatsheets#36]
How you manage this repo? Is it based on jekyll? 
Is there any way to get up and running with it quickly (like some kind of framework)? or Do we need to fork then delete your extra cheatsheets and then have to add our cheatsheets !

**Comment by rstacruz** [comment]
Hey there! That's not really a use case I made this repo for, so I
apologize for any lack of instructions. With that said, some people have
done just that--they just replaced the .md files with their own, like you
described.

It is a github pages site, so yes, it's managed by Jekyll. There's no
special setup here, just plain github pages.

Let me know if you need any help!

**Comment by collegeimprovements** [comment]
Sure. Thanks @rstacruz :)
