### ISSUE TITLE
easy history/edit/issue links

### ISSUE THREAD

**Issue by simonmichael** [rstacruz/cheatsheets#38]
Nice cheatsheet collection! 

I just noticed the Ledger and hledger ones. I wanted to suggest a change to the latter (deemphasize inacct:) but there was no obvious link. It might be nice to have links like "edit this page" (to submit a PR), "open issue" (against this cheatsheet), and "recent changes" (of this cheatsheet).

**Comment by rstacruz** [comment]
Oh, right! Yeah, we talked about that. Let me remove inacct.

As for edit links, I'd love that, don't have time to attend to that now though :(

(Thank you for hledger, I'd probably be broke without it)

**Comment by rstacruz** [comment]
Done, finally ;)
