### ISSUE TITLE
linkable headings on cheatsheet index

### ISSUE THREAD

**Issue by simonmichael** [rstacruz/cheatsheets#39]
On the cheatsheets front page, I wanted to link to the Ledger and hledger sections, but #ledger didn't seem to work.

**Comment by rstacruz** [comment]
Easy enough, thanks for the report! :green_heart:

**Comment by rstacruz** [comment]
Should be possible now: ricostacruz.com/cheatsheets/#ledger

Love to know what you think of the (h)ledger cheatsheets!
