### ISSUE TITLE
Use better quotes in font stack

### ISSUE THREAD

**Issue by cmegown** [rstacruz/cheatsheets#41]
This isn't a huge issue by any means but it would be nice to not have to replace the curly quotes around each font name in the `font-family` declaration at the top. I've come to this cheatsheet a few times to copy/paste the font stack and have had to replace the default quotes each time.

Better yet, could we make the font stack `monospace` and add click-to-copy? I could open a PR for it when I have the time.

**Comment by rstacruz** [comment]
Oh damn--didnt notice that! A pr is definitely appreciated.

**Comment by cmegown** [comment]
I'll take a crack at it!
