### ISSUE TITLE
Cheatsheet request: Angular2+

### ISSUE THREAD

**Issue by tmiles** [rstacruz/cheatsheets#421]
Angular2+ resources would be awesome to have - willing to help provide some examples. AngularJS is supported, but not angular2+

**Comment by niutech** [comment]
Angular cheat sheet is already [there](https://github.com/angular/angular/blob/master/aio/content/guide/cheatsheet.md), so could it be just copied here?

**Comment by tmiles** [comment]
I see it there, thanks for the link. It's not very easy to find on your devhints site though and no way to find angular2 stuff from search bar.

**Comment by chadwithuhc** [comment]
Closing in favor of #152
