### ISSUE TITLE
Did you block my IP address?

### ISSUE THREAD

**Issue by homologus** [rstacruz/cheatsheets#47]
I have been trying to learn from this cheatsheet theme, and then all of a sudden it stopped working. Looks like one of the style files has links to your site, and you blocked my IP addresses (207.115.89.242, 73.157.40.8) . Why would you do that for no reason?

**Comment by rstacruz** [comment]
Relax dude! I've migrated the domain to http://cloudflare.com/ and it'll take a while for DNS to re-propagate. You're not blocked :) Sorry for the inconvenience, but let me know if it still fails 24 hours from now.

**Comment by homologus** [comment]
Oh, good to know !! I recreated your style file from 'til' jekyll theme to continue working.

Nice theme, and thanks for sharing.

**Comment by homologus** [comment]
Hi, Just to let you know that I am able to access your blog and cheat sheets again.

Cheers, M
