### ISSUE TITLE
Cheatsheet request: React Native Documentation (Please see my simple on comment)

### ISSUE THREAD

**Issue by setkyar** [rstacruz/cheatsheets#477]
Hi, can you add RN Doc? I do get a reference from - https://rationalappdev.com/react-native-cheat-sheet and made a simple cheat sheet. 

### Build Project with Native Code

	react-native init AppName

### React Native without Build

	create-react-native-app AwesomeProject

  #### If you want to eject

    yarn run eject or npm run eject

### React Native run on simulator

    ios - $ react-native run-ios

    android - $ react-native run-android

    ios-by-device - $ react-native run-ios --simulator "iPhone 7 Plus"

### Linking Dependencies

	react-native link

### Upgrading React Native
	
	//upgrade to latest version
	npm install --save react-native@latest
	
	//upgrade project files
	react-native upgrade;

### Upgrading NPM Packages

	//To list all outdated packages execute:
	npm outdated
	
	//To update a package to the latest version execute:
	npm install --save package-name@latest;

###  Show/Hide Dev Menu

	//For ios
	⌘ + D
	
	//For Android
	⌘ + M

### Detecting Screen Size

	import  { Dimensions } from 'react-native';  
	const  { width, height }  = Dimensions.get('window'); 
	alert(Screen size: ${width}x${height});

### Limiting Number of Lines for Text Component

	<Text numberOfLines={2}> 
	Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam tincidunt eu neque non varius. 
	Phasellus id arcu in enim sodales sodales. Vestibulum maximus hendreri
	</Text>

### Component Boilerplate

    import React, { Component } from 'react';
    import {
      StyleSheet,
      Text,
      View
    } from 'react-native';

    export default class Component extends Component {

      render() {
        return (
          <View style={styles.container}>
            <Text>Component</Text>
          </View>
        );
      }

    }

    const styles = StyleSheet.create({
      container: {
        flex: 1,
      },
    });

### Default Prop Values

    import React, { Component } from 'react';
    import {
      StyleSheet,
      Text,
      View
    } from 'react-native';

    export default class Header extends Component {

      static defaultProps = {
        title: 'Default Header'
      }

      render() {
        return (
          <View >
            <Text style={styles.header}>
              {this.props.title.toUpperCase()}
            </Text>
          </View>
        );
      }

    }

    const styles = StyleSheet.create({
      header: {
        fontFamily: 'Avenir',
        fontSize: 40,
        fontWeight: 'bold',
        textAlign: 'center',
      },
    });

### Spread Attributes

    render() {
      const props = {
        title: 'My Title',
        size: 20,
      };
      return <Header {...props} />;
    }

Above code is same as the following

    render() {
	  const props = {
        title: 'My Title',
        size: 20,
      };
      return <Header title="My Title" size={20} />;
    } 

### Applying Multiple Styles to a Component

```
<View style={[styles.generic, styles.specific, { color: 'blue' }]} />
```

### Making a Circle

	<View style={{
	  width: 90,
	  height: 90,
	  borderRadius: 90 / 2,
	  backgroundColor: '#2196F3'
	}}/>

**Comment by chadwithuhc** [comment]
Closing in favor of #58
