### ISSUE TITLE
Windows CLI Cheatsheets

### ISSUE THREAD

**Issue by dellasorte** [rstacruz/cheatsheets#515]
Hi all. First of all thank all cobtributors and site creators. Cheatsheet are really helpful even for experienced developers. 

I didn't saw cheatsheet for windows command-line (cmd) and powershell CLIs . Is there any reason to ignore them? Guess it will be helpful for someone too.

**Comment by gretel** [comment]
@dellasorte could you point to the ones you are referring to please?

**Comment by chadwithuhc** [comment]
Duplicate of #193
