### ISSUE TITLE
Cheatsheet request: Vue.js

### ISSUE THREAD

**Issue by reds7373** [rstacruz/cheatsheets#57]
Hi,
Can you please get Vue.js cheetsheet?

Thanks,
Narasimha Reddy.

**Comment by rstacruz** [comment]
There's ricostacruz.com/cheatsheets/vue - not really complete though, so improvements are welcome :)

**Comment by Cyrille37** [comment]
https://devhints.io/vue

**Comment by chadwithuhc** [comment]
An update is needed, but this is available now at https://devhints.io/vue
