### ISSUE TITLE
Cheatsheet request: Kotlin

### ISSUE THREAD

**Issue by mustapha-hadid** [rstacruz/cheatsheets#582]
Kotlin is the second most loved language in [Stackoverflow survey 2018](https://insights.stackoverflow.com/survey/2018#most-loved-dreaded-and-wanted)!

**Comment by AdamMc331** [comment]
Hey @mustapha-hadid I've submit a PR for this! Let me know your initial thoughts. https://github.com/rstacruz/cheatsheets/pull/724

**Comment by AdamMc331** [comment]
Also, any chance we can close this as a duplicate of #94?

**Comment by chadwithuhc** [comment]
Duplicate of #94
