### ISSUE TITLE
Cheatsheet request: dart

### ISSUE THREAD

**Issue by weaming** [rstacruz/cheatsheets#588]
Missing dart lang

**Comment by chadwithuhc** [comment]
Duplicate of #264

**Comment by faisalaffan** [comment]
I would like to work on this issue. I already created a PR on this #2219 

![Dart cheatsheet](https://raw.githubusercontent.com/rstacruz/cheatsheets/d7b5037b41250c6eaeab88d403c8e1465ea5fbec/.github/images/dart-screenshot.png)
