### ISSUE TITLE
Cheatsheet request: Absinthe (GraphQL for Elixir)

### ISSUE THREAD

**Issue by turbofail** [rstacruz/cheatsheets#61]

**Comment by rstacruz** [comment]
started on this! https://devhints.io/wip/absinthe

**Comment by rstacruz** [comment]
And speaking of GraphQL, https://devhints.io/graphql has been updated as well

**Comment by chadwithuhc** [comment]
These exist at https://devhints.io/absinthe and https://devhints.io/graphql
