### ISSUE TITLE
Cheatsheet request: kubernetes

### ISSUE THREAD

**Issue by xubinzheng** [rstacruz/cheatsheets#617]
that would be really nice to have something for kubernetes/kubectl

https://kubernetes.io/docs/reference/kubectl/cheatsheet/
the official one is kind of messy 

Thanks

**Comment by fmoliveira** [comment]
Adding link posted in duplicate #711 for reference: https://files.acrobat.com/a/preview/5f7379e6-8331-4b90-ac64-691190c06ad3

**Comment by fmoliveira** [comment]
Comment by @cnowacek in duplicate request #647:

```
kubectl, example spec.yaml snippets, etc.
```

**Comment by fmoliveira** [comment]
I'm not familiar with Kubernetes so I don't know how other issues #324, #326, #419 and #520 relate to this one.

This is the oldest issue I've found mentioning kubectl so I copied suggestions from duplicates here to help things moving. 😄

**Comment by chadwithuhc** [comment]
Duplicate of #324
