### ISSUE TITLE
Cheatsheet request: KOTLIN

### ISSUE THREAD

**Issue by donpaul120** [rstacruz/cheatsheets#720]
Kotlin Cheat Sheet will be a good one, i could assist with this if you want.

**Comment by AdamMc331** [comment]
This would be great! I am more than happy to contribute to this as well. @donpaul120 Let me know if you'd like to collaborate on the content for it.

**Comment by AdamMc331** [comment]
I got started on this. Let me know what you think: https://github.com/rstacruz/cheatsheets/pull/724

**Comment by AdamMc331** [comment]
Also, any chance we can close this as a duplicate of #94?

**Comment by donpaul120** [comment]
@AdamMc331 Sure... we can

**Comment by donpaul120** [comment]
@AdamMc331  Nice on.. i got your message late.. You've pretty covered alot on it already.

**Comment by AdamMc331** [comment]
Happy to hear any feedback though if you feel anything is missing. :)

**Comment by chadwithuhc** [comment]
Duplicate of #94
