### ISSUE TITLE
Cheatsheet Enhancement: Sqlite 

### ISSUE THREAD

**Issue by sytabaresa** [rstacruz/cheatsheets#731]
Hello,
I see that bash cheatsheet don't have a very common for loop mode for multiline commands:
```bash
for elem in $(some-command); do
  echo $elem
done
```
and for single element for loop:

```bash
for elem in a b c; do
  echo $elem
done
```
maybe this can be very educational for the readers.

thank you

**Comment by chadwithuhc** [comment]
Duplicate of #675
