### ISSUE TITLE
Cheatsheet request: kotlin

### ISSUE THREAD

**Issue by mx1700** [rstacruz/cheatsheets#94]
http://kotlinlang.org/
thinks!

**Comment by AdamMc331** [comment]
Hey @mx1700 I've submit a PR, let me know what you think: https://github.com/rstacruz/cheatsheets/pull/724

**Comment by chadwithuhc** [comment]
Kotlin is now available! https://devhints.io/kotlin

If you see anything to add or change, please submit a PR.
